name: Integration tests
on:
  workflow_dispatch:
  schedule:
    - cron: '22 20 * * 1'

jobs:
  intro-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        node: [14]
        include:
          - os: ubuntu-18.04
            node: 12

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          npm ci
          npm run-script build

      - name: install
        shell: bash
        run: |
          ./contrib/tools/eslint/installers/install.sh ${ESLINT}
          ./contrib/tools/codeql/installers/install.sh ${CODEQL}
          ./contrib/tools/nodejsscan/installers/install.sh ${NJSSCAN}
        env:
          ESLINT: ${{ runner.temp }}/eslint-dir
          CODEQL: ${{ runner.temp }}/codeql-dir
          NJSSCAN: ${{ runner.temp }}/njsscan-dir
      - name: test
        run: |
          npx jest test/integration-tests/slow/multiple-tools-multiple-cves.test.ts
        env:
          CVEB_INTEGRATION_TEST_TOOLS: "{\"ideal-analysis\": {\"bin\":\"node\",\"args\":[\"build/ts/contrib/tools/ideal-analysis/src/ideal-analysis.js\"]}, \"eslint\": {\"bin\":\"node\",\"args\":[\"build/ts/contrib/tools/eslint/src/eslint.js\"],\"options\":{\"eslintDir\":\"${{ runner.temp}}/eslint-dir\"}}, \"codeql\": {\"bin\":\"node\",\"args\":[\"build/ts/contrib/tools/codeql/src/codeql.js\"],\"options\":{\"codeql\":\"${{ runner.temp }}/codeql-dir/codeql/codeql\"}}, \"nodejsscan\": {\"bin\":\"node\",\"args\":[\"build/ts/contrib/tools/nodejsscan/src/nodejsscan.js\"],\"options\":{\"njsscanDir\":\"${{ runner.temp}}/njsscan-dir\"}}}"
